### ISSUE TITLE
Project about

### ISSUE THREAD

**Issue by aronmal** [solidflow-org/solid-start-oauth#1]
This project seems very WIP. Linked website is not reachable, unknown origin or missing contact for @solidflow-org. And also, despite the fitting read-me file, it does not seem very feature rich. It was recommended by someone to me (here: https://github.com/nextauthjs/next-auth/issues/7889#issuecomment-1710175121), I do not feel convinced this is a replacement for next-auth nor my use case.

But because I recently switched to experiment with solidjs and probably want to use it more in the future, what can one expect from this project?

Because the discussions tab is not enabled, I try to reach out here in an issue. Well, there isn't any other contact information or possibility given at this point.

**Comment by solidflow-org** [comment]
Hello @aronmal, this package provides oauth only (as name implies) and uses solid-start sessions.
This is not a 'project', simply a package I've made for my needs and decided to share it.
For your case you can implement email auth ([official example](https://github.com/solidjs/solid-start/tree/main/examples/with-auth)) and share same session logic with the oauth.
